MiniShopApp.WebUI/Controllers/CardController.cs
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MiniShopApp.Business.Abstract;
using MiniShopApp.Core;
using MiniShopApp.Entity;
using MiniShopApp.WebUI.Identity;
using MiniShopApp.WebUI.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OrderItem = MiniShopApp.Entity.OrderItem;

namespace MiniShopApp.WebUI.Controllers
{
    [Authorize]
    public class CardController : Controller
    {
        private ICardService _cardService;
        private UserManager<User> _userManager;
        private IOrderService _orderService;

        public CardController(ICardService cardService, UserManager<User> userManager, IOrderService orderService)
        {
            _cardService = cardService;
            _userManager = userManager;
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);//autorize olunca olan userın ıdsını alır.
            var card = _cardService.GetCardByUserId(userId);
            return View(new CardModel()
            {
                CardId = card.Id,
                CardItems = card.CardItems.Select(i => new CardItemModel()
                {
                    CardItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.Name,
                    Price = (double)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            });
        }
        public IActionResult GetOrders()
        {
            var userId = _userManager.GetUserId(User);
            var orders = _orderService.GetOrders(userId);
            var orderListModel = new List<OrderListModel>();
            OrderListModel orderModel;
            foreach (var item in orders)
            {
                orderModel = new OrderListModel();
                orderModel.OrderId = item.Id;
                orderModel.OrderNumber = item.OrderNumber;
                orderModel.OrderDate = item.OrderDate;
                orderModel.FirstName = item.FirstName;
                orderModel.LastName = item.LastName;
                orderModel.Address = item.Address;
                orderModel.City = item.City;
                orderModel.Phone = item.Phone;
                orderModel.Email = item.Email;
                orderModel.OrderState = item.OrderState;
                orderModel.PaymentType = item.PaymentType;
                orderModel.OrderItems = item.OrderItems.Select(i => new OrderItemModel()
                {
                    OrderItemId = i.Id,
                    Name=i.Product.Name,
                    Price=(double)i.Price,
                    Quantity=i.Quantity,
                    ImageUrl=i.Product.ImageUrl
                }).ToList();
                orderListModel.Add(orderModel);
            }
            return View("Orders",orderListModel);
        }
        [HttpPost]
        public IActionResult AddToCard(int productId, int quantity)
        {
            var userId = _userManager.GetUserId(User);
            _cardService.AddToCard(userId, productId, quantity);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult DeleteFromCard(int productId)
        {
            var userId = _userManager.GetUserId(User);
            _cardService.DeleteFromCard(userId, productId);
            return RedirectToAction("Index");
        }
        public IActionResult CheckOut()
        {
            var userId = _userManager.GetUserId(User);
            var card = _cardService.GetCardByUserId(userId);
            var orderModel = new OrderModel();
            orderModel.CardModel = new CardModel()
            {
                CardId = card.Id,
                CardItems = card.CardItems.Select(i => new CardItemModel()
                {
                    CardItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.Name,
                    Price = (double)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity,

                }).ToList()
            };
            return View(orderModel);
        }
        [HttpPost]
        public IActionResult CheckOut(OrderModel orderModel)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var card = _cardService.GetCardByUserId(userId);
                orderModel.CardModel = new CardModel()
                {
                    CardId = card.Id,
                    CardItems = card.CardItems.Select(i => new CardItemModel()
                    {
                        CardItemId = i.Id,
                        ProductId = i.ProductId,
                        Name = i.Product.Name,
                        Price = (double)i.Product.Price,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity
                    }).ToList()
                };
                if (!CardNumberControl(orderModel.CardNumber))
                {
                    TempData["Message"] = JobManager.CreateMessage("Hata", "Kart Numarası Hatalıdır", "danger");
                    _cardService.ClearCard(orderModel.CardModel.CardId);
                    return View(orderModel);
                }
                //Ödeme alma işlemlerine başlayacağız
                var payment = PaymentProcess(orderModel);
                if (payment.Status=="success")
                {
                    TempData["Message"] = JobManager.CreateMessage("BAŞARILI", "Ödemeniz başarıyla alınmıştır", "success");
                    _cardService.ClearCard(orderModel.CardModel.CardId);
                    return View("Success");
                }
                else
                {
                    TempData["Message"] = JobManager.CreateMessage("BAŞARISIZ",payment.ErrorMessage, "danger");
                }
            }
            return View(orderModel);
        }

        private bool CardNumberControl(string cardNumber)
        {
            var cardNumberLength = cardNumber.Length;
            int total=0;
            if (cardNumberLength!=16)
            {
                return false;
            }
            else
            {
                int ovenTotal = 0;
                int oddTotal = 0;
                for (int i = 0; i < cardNumberLength; i++)
                {
                    int nextNumber =int.Parse((cardNumber[i].ToString()));
                    if (i%2==0)
                    {
                        oddTotal += NumberControl((nextNumber * 2).ToString());
                    }
                    else
                    {
                        ovenTotal += nextNumber;
                    }
                }
                total = ovenTotal + oddTotal;
            }
            if (total%10==0)
            {
                return true;
            }
            return false;
        }
        private int NumberControl(string number)
        {
            int numberLegth = number.Length;
            if (numberLegth==1)
            {
                return Convert.ToInt32(number);
            }
            int total = 0;
            for (int i = 0; i < numberLegth; i++)
            {
                total += Convert.ToInt32(number[i].ToString());
            }
            return total;
        }
        private void SaveOrder(OrderModel orderModel, Payment payment, string userId)
        {
            var order = new Order();
            order.OrderNumber = new Random().Next(111111111, 999999999).ToString();
            order.OrderState = EnumOrderState.Completed;
            order.PaymentType = EnumPaymentType.CreditCard;
            order.PaymentId = payment.PaymentId;
            order.ConversationId = payment.ConversationId;
            order.OrderDate = new DateTime();
            order.FirstName = orderModel.FirstName;
            order.LastName = orderModel.LastName;
            order.Phone = orderModel.Phone;
            order.Email = orderModel.Email;
            order.UserId = userId;
            order.Address = orderModel.Address;
            order.City = orderModel.City;
            order.OrderItems = new List<OrderItem>();
            foreach (var item in orderModel.CardModel.CardItems)
            {
                var orderItem = new OrderItem()
                {
                    Price=item.Price,
                    Quantity=item.Quantity,
                    ProductId=item.ProductId,
                };
                order.OrderItems.Add(orderItem);
            }
            //Artık bu bilgileri kullanarak order kaydı yaratabılırız
            _orderService.Create(order);
        }

        private Payment PaymentProcess(OrderModel orderModel)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-WNeTysts76e7tPEGfEl6pdikI4q73neG";
            options.SecretKey = "sandbox-sAhINCxSAQwY1YUiK5qs9FANl4gdfIjz";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";

            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = new Random().Next(111111111,999999999).ToString();
            request.Price = orderModel.CardModel.TotalPrice().ToString();
            request.PaidPrice = orderModel.CardModel.TotalPrice().ToString();//indiirm felan olrusa burda yazılır ona gore odeme alınır
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = "B67832";
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

MiniShopApp.WebUI/Controllers/MiniShopController.cs
using Microsoft.AspNetCore.Mvc;
using MiniShopApp.Business.Abstract;
using MiniShopApp.Entity;
using MiniShopApp.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MiniShopApp.WebUI.Controllers
{
    public class MiniShopController : Controller
    {
        private IProductService _productService;
        public MiniShopController(IProductService productService)
        {
            _productService=productService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List(string category, int page=1)
        {
            ViewBag.Message = "Ürün bulunamadı";
            ViewBag.AlertType = "warning";
            //ÖDEV:
            //Bu işi ister model kullanarak şu an olduğu gibi partial yapıyla
            //İsterseniz ise daha farklı bir yol olarak ViewComponent mantığıyla
            //Çözün.

            //***********************************

            const int pageSize = 5;//bu değişken her sayfada kaç item görüneceğini tutacak
            int totalItems = _productService.GetCountByCategory(category);
            var productListViewModel = new ProductListViewModel()
            {
                PageInfo = new PageInfo
                {
                    TotalItems= totalItems,
                    CurrentPage= page,
                    ItemsPerPage= pageSize,
                    CurrentCategory = category
                },
                Products= _productService.GetProductsByCategory(category, page, pageSize)
            };
            return View(productListViewModel); 
        }

        public IActionResult Details(string url)
        {
            if (url==null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails(url);
            if (product==null)
            {
                return NotFound();
            }
            ProductDetailModel productDetail = new ProductDetailModel()
            {
                Product = product,
                Categories = product.ProductCategories.Select(i => i.Category).ToList() 
            };
            return View(productDetail);  
        }

        public IActionResult Search(string q)
        {
            //Bize arama kriterinin (q) uygun olduğu, eşleştiği TÜM ÜRÜNLERİ
            //döndürecek bir METOT lazım.
            return View(_productService.GetSearchResult(q)); 
        }
    }
}

MiniShopApp.WebUI/ViewComponents/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MiniShopApp.Business.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MiniShopApp.WebUI.ViewComponents
{
    public class CategoriesViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoriesViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (RouteData.Values["category"]!=null)
            {
                ViewBag.SelectedCategory = RouteData.Values["category"];
            }
            var categories = await _categoryService.GetAll();
            return View(categories);
        }
    }
}

MiniShopApp.WebUI/Views/MiniShop/Details.cshtml
@model ProductDetailModel

    <div class="row">
        <div class="col-md-2">
            <img src="~/img/@Model.Product.ImageUrl" class="img-fluid" alt="Alternate Text" />
        </div>
        <div class="col-md-10">
            <h1 class="mb-3">@Model.Product.Name</h1>
            <hr />
            @foreach (var item in Model.Categories) 
            {
                <a 
                   asp-controller="MiniShop"
                   asp-action="List"
                   asp-route-category="@item.Url"
                   class="btn btn-link p-0 mb-3">@item.Name </a>  
            }
            <div class="mb-3">
                <h4 class="text-primary">@Model.Product.Price <i class="fa-solid fa-turkish-lira-sign"></i></h4>
                <div class="mb-3">
                    <p>@Model.Product.Description</p>
                </div>
                <form asp-controller="Card" asp-action="AddToCard" method="post" class="form-inline">
                    <input type="hidden" name="productId" value="@Model.Product.ProductId" />
                    <div class="input-group w-25">
                        <div>
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-shopping-cart"></i>
                            Add to Card</button>
                        </div>
                        <input type="number" class="form-control ms-2" name="quantity" value="1" min="1" step="1" />
                    </div>
                </form>
                
            </div>
        </div>
    </div>

MiniShopApp.WebUI/Views/MiniShop/List.cshtml
@model ProductListViewModel

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-9">
        <div class="row">
            @if (Model.Products.Count == 0)
            {
                <partial name="_NoProduct" />
            }
            else
            {
                @foreach (var product in Model.Products)
                {
                    <div class="col-md-4">
                        <partial name="_Product" model="product" />
                        @*@await Html.PartialAsync("_Product", product)*@
                    </div>
                }
            }
        </div>
        <div class="row">
            <div class="col">
                <nav>
                    <ul class="pagination">
                        @for (int i = 0; i < Model.PageInfo.TotalPages(); i++)
                        {
                            @if (string.IsNullOrEmpty(Model.PageInfo.CurrentCategory))
                            {
                                <li class="page-item @(Model.PageInfo.CurrentPage==i+1 ? "active" : "")">
                                    <a href="/products?page=@(i+1)" class="page-link">@(i+1)</a>
                                </li>
                            }
                            else
                            {
                                <li class="page-item @(Model.PageInfo.CurrentPage==i+1 ? "active" : "")">
                                    <a href="/products/@Model.PageInfo.CurrentCategory?page=@(i+1)" class="page-link">@(i+1)</a>
                                </li>
                            }
                        }



                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>

MiniShopApp.WebUI/Views/MiniShop/ProductEdit.cshtml
@model ProductModel
<h1 class="display-4">Edit Product</h1>
<hr />

<form as-controller="Admin" asp-action="ProductEdit" method="post">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group row mb-2">
                <label class="col-sm-3 col-form-label">Name</label>
                <div class="col-sm-9">
                    <input type="text" asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row mb-2">
                <label class="col-sm-3 col-form-label">Url</label>
                <div class="col-sm-9">
                    <input type="hidden" asp-for="ProductId" value="@Model.ProductId"/>
                    <input type="text" asp-for="Url" class="form-control" />
                </div>
            </div>
            <div class="form-group row mb-2">
                <label class="col-sm-3 col-form-label">Description</label>
                <div class="col-sm-9">
                    <input type="text" asp-for="Description" class="form-control" />
                </div>
            </div>
            <div class="form-group row mb-2">
                <label class="col-sm-3 col-form-label">Image Url</label>
                <div class="col-sm-9">
                    <input type="text" asp-for="ImageUrl" class="form-control" />
                </div>
            </div>
            <div class="form-group row mb-2">
                <label class="col-sm-3 col-form-label">Price</label>
                <div class="col-sm-9">
                    <input type="text" asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row mb-2">
                <div class="col-sm-9">
                    <button type="submit" class="btn btn-success">Save Product</button>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            @foreach (var item in (List<Category>)ViewBag.Categories)
            {
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" name="categoryIds" value="@item.CategoryId" id="category_@item.CategoryId"
                           @if (Model.SelectedCategories!=null)
                           {
                               @(Model.SelectedCategories.Any(i=>i.CategoryId==item.CategoryId)? "checked" : "")
                           } 
                           />
                    <label class="form-check-label">@item.Name</label>
                </div>
            }
            <hr />
            <div class="form-check">
                <input type="checkbox" asp-for="IsApproved" class="form-check-input" />
                <label class="form-check-label">Is Approved?</label>
            </div>
            <div class="form-check">
                <input type="checkbox" asp-for="IsHome" class="form-check-input" />
                <label class="form-check-label">Is Home?</label>
            </div>
        </div>
    </div>
</form>

MiniShopApp.WebUI/Views/MiniShop/Search.cshtml
@model List<Product>
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("Categories")
        </div>
        <div class="col-md-9">
            <div class="row">
                @foreach (var product in Model)
                {
                    <div class="col-md-4">
                        <partial name="_Product" model="product" />
                    </div>
                }
            </div>
        </div>
    </div>